# Generated by Django 5.2.8 on 2025-12-01 13:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_formationspage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemoignagesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('auteur', models.CharField(blank=True, max_length=255)),
                ('contenu', wagtail.fields.RichTextField(blank=True)),
                ('temoignages_blocks', wagtail.fields.StreamField([('temoignage', 5)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.IntegerBlock', (), {'max_value': 5, 'min_value': 1, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('texte', 0), ('photo', 1), ('nom', 2), ('poste', 3), ('note', 4)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
